import{S as h,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/",L="49374339-6c81470c324f76695f53d1c98";async function m(t,r=1,n=15){const s=new URLSearchParams({key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}),e=await fetch(`${b}?${s}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}let d;function p(t,r=!1){const n=document.querySelector(".gallery"),s=t.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      </a>
      <div class="image-info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");r?n.insertAdjacentHTML("beforeend",s):n.innerHTML=s,d?d.refresh():d=new h(".gallery a",{captionsData:"alt",captionDelay:250})}function w(){var t;document.querySelector(".gallery").innerHTML="",(t=document.querySelector(".end-message"))==null||t.remove()}function y(){document.querySelector(".loader").style.display="block"}function g(){document.querySelector(".loader").style.display="none"}function a(t=!0){document.querySelector(".load-more").style.display=t?"block":"none"}function S(){const t=document.createElement("p");t.textContent="We're sorry, but you've reached the end of search results.",t.classList.add("end-message"),document.querySelector(".gallery-container").appendChild(t)}function q(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}let i=1,c="",f=0;document.querySelector(".form").addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target["search-text"].value.trim(),!c){l.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}i=1,y(),a(!1),w();try{const r=await m(c,i);if(f=r.totalHits,r.hits.length===0){l.info({title:"Info",message:"No images found for your query",position:"topRight"});return}p(r.hits),r.hits.length<f&&a(!0)}catch(r){l.error({title:"Error",message:r.message,position:"topRight"})}finally{g()}});document.querySelector(".load-more").addEventListener("click",async()=>{i++,y(),a(!1);try{const t=await m(c,i);p(t.hits,!0),q(),i*15>=f?(a(!1),S()):a(!0)}catch(t){l.error({title:"Error",message:t.message,position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
